spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/nucms?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
  
  security:
    user:
      name: user
      password: root

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.nucms.**.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    egovframework: debug
    com.nucms: debug

cms:
  file:
    upload-path: c:/Users/asus/dev/nu-CMS/uploads
